### ISSUE TITLE
Include environment.yml

### ISSUE THREAD

**Issue by babaid** [ghorbanimahdi73/autofragdiff#1]
The list of packages in the `README.md` does not actually contain every package needed. I have a suggestion for an `environment.yml` that contains every package needed to run scripts and the example notebook: 

```yaml
name: autofragdiff2
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
  - pyg
  - rdkit
dependencies:
  - openbabel<=3.1.1
  - pytorch<=2.0.1
  - pytorch-cuda<=11.8
  - biopython<=1.81 
  - biopandas<=0.4.1 
  - -fpocket
  - torch-scatter
  - vina
  - networkx<=3.1 
  - pyg 
  - py3dmol<=2.0.1
  - scikit-learn<=1.2.2
  - tensorboard<=2.13.0
  - wandb<=0.15.2
  - tqdm
  - pytorch-lightning<=1.6.0
  - mkl<=2024.0
  - meeko
  - mgltools
  - rdkit<=2023.3.1
  - jupyterlab
  - ipykernel
  - pip: 
    - git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3
```

This should cover every package needed and is more convenient for someone who wants to use autofragdiff.
